language: generic

dist: trusty
sudo: false

env:
  global:
  - HELM_LATEST_VERSION="v2.5.1"

install:
- wget http://storage.googleapis.com/kubernetes-helm/helm-${HELM_LATEST_VERSION}-linux-amd64.tar.gz -O /tmp/helm.tar.gz
- tar xzf /tmp/helm.tar.gz -C /tmp --strip-components=1
- chmod +x /tmp/helm

before_script:
- /tmp/helm init --client-only
- /tmp/helm repo add stable https://kubernetes-charts.storage.googleapis.com
- |
  for chart in $(find . -name 'requirements.yaml'); do
    /tmp/helm dep build $(dirname ${chart})
  done

script:
- /tmp/helm lint */

# after_success:
# - |
#   SOURCE_BRANCH='master'
  
#   # Skip if PR or not master branch
#   if [ "$TRAVIS_PULL_REQUEST" != "false" -o $TRAVIS_BRANCH != $SOURCE_BRANCH ]; then
#       echo "Not a tag. Skipping chart repository publish."
#       exit 0
#   fi
  
#   # Decrypt deploy key and add to SSH
#   openssl aes-256-cbc -K $encrypted_1314893fce55_key -iv $encrypted_1314893fce55_iv -in deploy_key.enc -out deploy_key -d
#   chmod 600 deploy_key
#   eval `ssh-agent -s`
#   ssh-add deploy_key
  
#   # Update the charts repository (GitHub Pages)
#   ./updateChartsRepository.sh

